fixing indentation for the mfatool script

diff --git a/bin/mfatool b/bin/mfatool
--- a/bin/mfatool
+++ b/bin/mfatool
@@ -55,21 +55,20 @@ mfakey=''
 totp_key=''
 function get_mfatoken {
 
-	mfakey=$(oathtool --base32 --totp "$(secret-tool lookup labmfatool 2016_01_10 username "${1}" service "${2}")")
+  mfakey=$(oathtool --base32 --totp "$(secret-tool lookup labmfatool 2016_01_10 username "${1}" service "${2}")")
 
-	if [[ $nullmfakey == "${mfakey}" ]]; then
-	  printf "%sNot Found:%s no MFA key found in keychain for %s%s%s@%s%s%s\n" "${bldred}" "${txtrst}" "${txtylw}" "${1}" "${txtrst}" "${txtylw}" "${2}" "${txtrst}"; 
-	  exit 3;
+  if [[ $nullmfakey == "${mfakey}" ]]; then
+    printf "%sNot Found:%s no MFA key found in keychain for %s%s%s@%s%s%s\n" "${bldred}" "${txtrst}" "${txtylw}" "${1}" "${txtrst}" "${txtylw}" "${2}" "${txtrst}"; 
+    exit 3;
 
-	else
-	  printf "MFA token for %s%s%s @ %s%s%s :\t%s%s%s\n" "${txtylw}" "${1}" "${txtrst}" "${txtylw}" "${2}" "${txtrst}" "${bldgrn}" "${mfakey}" "${txtrst}";
-	fi
+  else
+    printf "MFA token for %s%s%s @ %s%s%s :\t%s%s%s\n" "${txtylw}" "${1}" "${txtrst}" "${txtylw}" "${2}" "${txtrst}" "${bldgrn}" "${mfakey}" "${txtrst}";
+  fi
 }
 
 function output_qr_utf8 {
   #test for qrencode dependency
   type qrencode >/dev/null 2>&1 || { printf >&2 "%sERROR: %s I require %s'qrencode'%s command but it's not installed or not in the PATH.  Aborting.\n" "${bldred}" "${txtrst}" "${txtylw}" "${txtrst}"; exit 1; }
-  #type qrencode >/dev/null 2>&1 || { printf >&2 "${bldred}ERROR: ${txtrst} I require 'qrencode' command but it's not installed or not in the PATH.  Aborting.\n"; exit 1; }
   get_totp_keys "${1}" "${2}"
   qrencode -t UTF8 "otpauth://totp/${2}:${1}?secret=${totp_key}"
   exit 0;
@@ -94,9 +93,9 @@ if [[ "$1" == '--help'||"$1" == '-h' ]]; then
 fi
 
 if [[ "$1" == '--list' ]]; then
-	secret-tool search --all labmfatool 2016_01_10 2>/dev/null |grep "label = "|sed 's/\(.*\)@/\1 /' |awk '{print $3 " " $4}'
+  secret-tool search --all labmfatool 2016_01_10 2>/dev/null |grep "label = "|sed 's/\(.*\)@/\1 /' |awk '{print $3 " " $4}'
 
-	exit 0;
+  exit 0;
 fi
 
 if [[ "$1" == '--all' ]] || [[ "$1" == '--export' ]]; then
@@ -107,7 +106,7 @@ if [[ "$1" == '--all' ]] || [[ "$1" == '--export' ]]; then
     elif [[ "$1" == '--export' ]]; then
       get_totp_keys "${user}" "${domain}"
     fi
-	done <<< "$ACCOUNTLIST"
+  done <<< "$ACCOUNTLIST"
   
   exit 0;
 fi
@@ -145,7 +144,5 @@ fi
 if [[ "$1" == '--store' ]]; then
   secret-tool store --label "${emailaddr}@${service}" labmfatool 2016_01_10 username "${emailaddr}" service "${service}"
 else
-	get_mfatoken "${emailaddr}" "${service}"
+  get_mfatoken "${emailaddr}" "${service}"
 fi
-
-  
