updated qr function fixed logic and parameter usage is now scoped correctly

diff --git a/bin/mfatool b/bin/mfatool
--- a/bin/mfatool
+++ b/bin/mfatool
@@ -44,7 +44,8 @@ Examples:
 "
 
 nullmfakey=$(oathtool --base32 --totp "")
-
+mfakey=''
+totp_key=''
 function get_mfatoken {
 
 	mfakey=$(oathtool --base32 --totp "$(secret-tool lookup labmfatool 2016_01_10 username "${1}" service "${2}")")
@@ -60,16 +61,15 @@ function get_mfatoken {
 
 function output_qr_utf8 {
   #test for qrencode dependency
-  type qrencode >/dev/null 2>&1 || { printf >&2 "${bldred}ERROR: ${txtrst} I require 'qrencode' command but it's not installed or not in the PATH.  Aborting.\n"; exit 1; }
-  get_totp_keys "${emailaddr}" "${service}"
-  set -x
-  qrencode -t UTF8 "otpauth://totp/${service}:${emailaddr}?secrete=${mfakey}"
+  type qrencode >/dev/null 2>&1 || { printf >&2 "${bldred}ERROR: ${txtrst} I require ${txtylw}'qrencode'${txtrst} command but it's not installed or not in the PATH.  Aborting.\n"; exit 1; }
+  #type qrencode >/dev/null 2>&1 || { printf >&2 "${bldred}ERROR: ${txtrst} I require 'qrencode' command but it's not installed or not in the PATH.  Aborting.\n"; exit 1; }
+  get_totp_keys "${1}" "${2}"
+  qrencode -t UTF8 "otpauth://totp/${2}:${1}?secret=${totp_key}"
   exit 0;
   
 }
 
 function get_totp_keys {
-  set -x
   totp_key=$(secret-tool lookup labmfatool 2016_01_10 username "${1}" service "${2}")
 
   if [[ $nullmfakey == "$totp_key" ]]; then
@@ -114,7 +114,7 @@ fi
 emailaddr=$1
 service=$2
 
-if [ "$1" -eq '--store' ] || [ "$1" -eq '--qr']; then
+if [[ "$1" -eq '--store' ]] || [[ "$1" -eq '--qr' ]]; then
 	emailaddr=$2
   service=$3
 fi
